"""empty message

Revision ID: 4cbca066f1a4
Revises: 
Create Date: 2017-05-02 17:37:13.467045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbca066f1a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('talk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talk_id', sa.Unicode(length=255), nullable=True),
    sa.Column('credential', sa.Unicode(length=1200), nullable=True),
    sa.Column('calendar_id', sa.Unicode(length=200), nullable=True),
    sa.Column('up_to_day_flag', sa.Boolean(), nullable=True),
    sa.Column('day_flag', sa.Boolean(), nullable=True),
    sa.Column('date_flag', sa.Boolean(), nullable=True),
    sa.Column('keyword_flag', sa.Boolean(), nullable=True),
    sa.Column('calendar_select_flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('talk_id')
    )
    op.create_table('free_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_name', sa.Unicode(length=255), nullable=True),
    sa.Column('talk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talk_id'], ['talk.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'user_name', 'talk_id', name='_date_user_name_talk_id_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('free_day')
    op.drop_table('talk')
    op.drop_table('sessions')
    # ### end Alembic commands ###
